services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

  localgateway:
    build:
      context: ./LocalGateway
      dockerfile: Dockerfile
    container_name: localgateway
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - authmodule
      - mainmodule

  authmodule:
    build:
      context: ./AuthModule
      dockerfile: Dockerfile
    container_name: authmodule
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AppDb;Username=postgres;Password=postgres
      - Jwt__Issuer=swovnai
      - Jwt__Audience=swovnai
      - Jwt__Secret=${JWT_SECRET}
    depends_on:
      - postgres
    env_file:
      - .env

  mainmodule:
    build:
      context: ./MainModule
      dockerfile: Dockerfile
    container_name: mainmodule
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AppDb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
